sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: vyz4u2h+w6R6U8Tj/xW6J2rMqqRxS9vYzfpPwzH+Axd8AiIPK6SCLGgsvMjXWiXpwW7yCXM71o/H8y0ylbbTw8zUz9nGpIb/bOvMRIpyrMB/XfdiYzAMo69Q13nGYudVhffS+CcJ/PAn8O6aDLxsVdlQZ8bXY/UdcXKekALiLCVAW5tqIqbMuRZtHx4SQGBKxhMDJyBl/rVYxEPs77ukOa1/WwHtzf30DXH2mv0Ufuwnx58pLHYffaVBqz/3YJGGUNM/pBfFiSMl0ICncZwnO3p8miWUiUkYFtvscFaa89Ii1DvooqP3kk02fzHkuGZZ1eMMsStnlXhV1tDvfSZEDWByRj41u4BzCntic30N8vZQ94aybgarTe6b3DpCejjvGW6nVFdJBPrOUgb7jyD5I/XnO59zMe6vdSgIU1WVK4n4wcMIuMpZSqlrRqWsdlAgAiFHaOc+AITMcX2jl+N70VQ5toca6G4LYAbFQUraUPTzkPAAr0aQylA6CB1T3qksxXLYgBtC91jssnbmNwX+DKWmyn1w73U7Qh+EYyMdnTVd7lITI2mtC4/aUkpqvSlnZyTh0H9MHvNkJX7q4HggoZePG3Phg1TmBo6kqtdS80V+YNs047kB459v2q3uCgo97mqiU55MxlcaR/i9vkg5GwBjGfXvsUfhAUs2bTqDkW8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Memoirs-of-Marguerite-de-Valois-Queen-of-Navarre---Volume-2_3839
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy